-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, SUM(os.SALES_AMOUNT) * p.PRICE AS PRICE
FROM PRODUCT p
JOIN OFFLINE_SALE os ON os.PRODUCT_ID = p.PRODUCT_ID
GROUP BY os.PRODUCT_ID
ORDER BY PRICE DESC, p.PRODUCT_CODE ASC;