-- 코드를 입력하세요
SELECT 
	YEAR(os.SALES_DATE) AS YEAR,
	MONTH(os.SALES_DATE) AS MONTH,
	COUNT(DISTINCT ui.USER_ID) AS PUCHASED_USERS,
	ROUND(COUNT(DISTINCT ui.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE os
INNER JOIN USER_INFO ui ON os.USER_ID = ui.USER_ID
WHERE YEAR(ui.JOINED) = 2021
GROUP BY YEAR, MONTH;